name: hugodims
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- bcftools=1.3.1=1
- bedtools=2.26.0=0
- curl=7.45.0=2
- dropbox=5.2.1=py35_0
- filechunkio=1.6=py35_0
- ftputil=3.2=py35_0
- gatk=3.7=py35_0
- java-jdk=8.0.92=1
- perl-threaded=5.22.0=pl5.22.0_12
- perl-vcftools-vcf=0.953=3
- pysftp=0.2.8=py35_0
- samtools=1.3.1=5
- snakemake=3.10.1=py35_1
- urllib3=1.12=py35_0
- vcftools=0.1.14=4
- perl=5.22.0.1=0
- bzip2=1.0.6=3
- cffi=1.9.1=py35_0
- cryptography=1.7.1=py35_0
- docutils=0.13.1=py35_0
- idna=2.2=py35_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- openssl=1.0.2k=0
- paramiko=2.0.2=py35_0
- pip=9.0.1=py35_1
- pyasn1=0.1.9=py35_0
- pycparser=2.17=py35_0
- python=3.5.2=0
- pyyaml=3.12=py35_0
- readline=6.2=2
- requests=2.13.0=py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- wrapt=1.10.8=py35_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3

